
# cargo-vet audits file

[[audits.cc]]
who = "Billy Price <williamp@microsoft.com>"
criteria = "safe-to-deploy"
delta = "1.2.59 -> 1.2.60"

[[audits.embassy-executor]]
who = "Billy Price <williamp@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.9.1 -> 0.10.0"

[[audits.embassy-executor-macros]]
who = "Billy Price <williamp@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.7.0 -> 0.8.0"

[[audits.embassy-imxrt]]
who = "Kurtis Dinelle <kdinelle@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0@git:f3be03ca74bfefb062b4536848c2f1d1b7e06186"
importable = false
notes = "ODP-owned crate, internal dependency. Assisted-by: copilot-cli:claude-opus-4.6 cargo-vet"

[[audits.libc]]
who = "Billy Price <williamp@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.2.184 -> 0.2.185"
