[default.general]
chip = "MEC1723N_B0_SZ"

[default.rtt]
enabled = true
timeout = 5000

[default.probe]
protocol = "Swd"
speed = 4000

[default.flashing]
enabled = true

[default.reset]
halt_afterwards = false